model: UNET #VAE,UNET,GAN
### Data path
txt_file: './frontiers_dataset/submaps/index.txt'
root_dir: './frontiers_dataset'


# Optimization options
epochs: 1000 # 450
batch_size: 128
learning_rate: 1.0e-2 # 1.0e-4
momentum: 0.9
decay: 0.001 # Weight decay (L2 penalty)
schedule: [180, 450] # Decrease learning rate at these epochs.
gammas: [0.1, 0.01] # LR is multiplied by gamma on schedule, number of gammas should be equal to schedule

# Checkpoints
print_freq: 1 # 200
save_path: './save' # Folder to save checkpoints and log.
resume: '' # path to latest checkpoint (default: none)
start_epoch: 0


# evaluate: 

# Acceleration
num_gpu: 1
use_cuda: True
num_workers: 16

# Random seed
seed: 2020    # Optimization options

val_step: 1 # 20
vis_step: 1 # 20
checkpoint_step: 5
